{% set name = "instaseis" %}
{% set version = "1.3.0" %}
{% set sha256 = "97b30d80d51b6841d41f9266d95a44bf697a8b2dbe56b2b8e39eacd895f9b383" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1001
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
  run:
    - python
    - numpy
    - h5py
    - obspy
    - future
    - tornado >=5,<6
    - requests
    - jsonschema
    - pyqt
    - pyqtgraph
    - geographiclib
    - futures  # [py27]

test:
  imports:
    - instaseis
  requires:
    # Not having the next two will results in substantially fewer test to be
    # run. The travis OSX builder takes a long time otherwise and I'm
    # confident enough that everything works even without the additional
    # tests.
    - click  # [not osx]
    - netcdf4  # [not osx]
    - responses
    # see https://docs.pytest.org/en/latest/changelog.html#removals
    - pytest <5.1.0
    - pytest-xdist
    - mock  # [py27]
    - futures  # [py27]

about:
  home: http://instaseis.net
  license: LGPL-3.0 (for non-commercial/academic use)
  summary: 'Instant Global Broadband Seismograms Based on a Waveform Database'
  description: |
    Instaseis calculates broadband seismograms from Green's function databases
    generated with AxiSEM and allows for near instantaneous (on the order of
    milliseconds) extraction of seismograms. Using the 2.5D axisymmetric
    spectral element method, the generation of these databases, based on
    reciprocity of the Green's functions, is very efficient and is approximately
    half as expensive as a single AxiSEM forward run. Thus this enables the
    computation of full databases at half the cost of the computation of
    seismograms for a single source in the previous scheme and hence allows to
    compute databases at the highest frequencies globally observed. By storing
    the basis coefficients of the numerical scheme (Lagrange polynomials),
    the Green's functions are 4th order accurate in space and the spatial
    discretization respects discontinuities in the velocity model exactly. On
    top, AxiSEM allows to include 2D structure in the source receiver plane and
    readily includes other planets such as Mars.
  doc_url: http://instaseis.net
  dev_url: https://github.com/krischer/instaseis

extra:
  recipe-maintainers:
    - krischer
    - martinvandriel
    - sstaehler
